<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js([
    pi::url('static/js/html5shiv.js')   => [
        'conditional' => 'lt IE 9',
    ],
    pi::url('static/js/respond.min.js') => [
        'conditional' => 'lt IE 9',
    ],
]);

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap([
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css',
]);

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink([
    'rel'  => 'apple-touch-icon',
    'href' => $this->assetTheme('image/touch-icon-iphone.png'),
]);
// Apple icon for ipad
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png'),
]);
// Apple icon for iphone retina
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png'),
]);
// Apple icon for ipad retina
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png'),
]);

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink([
    'rel'  => 'shortcut icon',
    'type' => 'image/x-icon',
    'href' => $this->favicon(),
]);
$this->headLink([
    'rel'  => 'shortcut icon',
    'type' => 'image/png',
    'href' => $this->favicon('favicon.png'),
]);

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks        = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    ['prefix' => [
        [
            'label' => __('Home'),
            'href'  => Pi::url($this->url('home')),
        ],
    ]]
);

if ($module != 'user') {
    Pi::service('authentication')->requireLogin();
}
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<!-- Header: brand, slogan, user bar -->
<header class="pi-header">
    <div class="pi-header-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    <?php if ($module == 'system') { ?>
                        <h1>
                            <a href="<?php echo Pi::url($this->url('home')); ?>"
                               title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>"
                                     alt="<?php echo _escape($sitename); ?>">
                            </a>
                        </h1>
                    <?php } else { ?>
                        <h2>
                            <a href="<?php echo Pi::url($this->url('home')); ?>"
                               title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>"
                                     alt="<?php echo _escape($sitename); ?>">
                            </a>
                        </h2>
                    <?php } ?>
                </div>
                <div class="col-md-9">
                    <?php echo $this->widget('system-user-bar'); ?>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-header">
                        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                        <div class="navbar-form navbar-right">
                            <?php echo $this->widget('search-search'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- Top head zone -->
    <?php if (!empty($blocks['0'])) { ?>
        <div class="pi-zone-0">
            <?php foreach ($blocks['0'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
    <?php } ?>
</header>
<!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
<section class="pi-section">

    <div class="container-fluid">
        <div class="pi-main-container">
            <?php if ($breadcrumbs) {
                echo $breadcrumbs;
            } ?>
            <!-- Flash messenger -->
            <?php include $this->template('flash-messenger'); ?>

            <div class="row">
                <!-- Left zone -->
                <?php if (!empty($blocks['1'])) { ?>
                    <div class="pi-zone-1 col-md-4">
                        <?php foreach ($blocks['1'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-md-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-md-8';
                } else {
                    echo 'col-md-12';
                }
                ?>">
                    <!-- Center top zone -->
                    <?php if (isset($blocks['2'])) { ?>
                        <div class="pi-zone-2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-3">
                                <?php
                                if (isset($blocks['3'])) {
                                    foreach ($blocks['3'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-4">
                                <?php
                                if (isset($blocks['4'])) {
                                    foreach ($blocks['4'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Module content starts -->
                    <?php if (!empty($content)) { ?>
                        <div class="<?php echo $module; ?>">
                            <div class="pi-module-content" data-ng-app="<?php echo $module; ?>">
                                <?php echo $content; ?>
                            </div>
                            <?php echo Pi::service('comment')->load(['options' => ['type' => 'js']]); ?>
                        </div>
                    <?php } ?>
                    <!-- Module content ends -->
                    <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-5">
                                <?php
                                if (isset($blocks['5'])) {
                                    foreach ($blocks['5'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-6">
                                <?php
                                if (isset($blocks['6'])) {
                                    foreach ($blocks['6'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Center bottom zone -->
                    <?php if (isset($blocks['7'])) { ?>
                        <div class="pi-zone-7">
                            <?php foreach ($blocks['7'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Right zone -->
                <?php if (isset($blocks['8'])) { ?>
                    <div class="col-md-4 pi-zone-8">
                        <?php foreach ($blocks['8'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
            <!-- Bottom foot zone -->
            <?php if (isset($blocks['99'])) { ?>
                <div class="pi-zone-99">
                    <?php foreach ($blocks['99'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</section>
<section id="subscribe" class="bg-parallax pt100 pb100" style='background-image: url("<?php echo $this->assetTheme('image/bg3.jpg'); ?>")'>
    <div class="parallax-overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 mr-auto ml-auto text-center">
                <h3 class="text-center text-white title-font mb50"><?php echo _escape($sitename); ?></h3>
                <p class="text-white-gray text-center mb50">ترجمه رسمی اسناد و مدارک : دفتر رسمی  ( شماره 653 تهران) به عنوان اولین و تنها دفتر ترجمه رسمی 5 زبانه بی واسطه در کشور که کلیه ترجمه ها در کمترین زمان و با بالاترین کیفیت و بدون واسطه به شما مشتریان گرامی ارائه می نامید .                    رمز موفقیت ما در جلب رضایت مشتریان عدم واسطه گری و در نتیجه ارائه ترجمه هایی با نرخ مصوب اداره امور مترجمان قوه قضائیه است و از آنجائیکه تمامی ترجمه ها بی واسطه و تحت نظارت مترجمین رسمی انجام می شود ، ترجمه های ارائه شده در بالاترین کیفیت ممکن خواهد بود .</p>
            </div>
        </div>
    </div>
</section>
<footer class="pi-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 text-center">
                <ul class="list-unstyled">
                    <li class="pt20"> تمام حقوق مطالب برای وب سایت <a title="<?php echo _escape($sitename); ?>" href="https://www.cafeyab.com"><?php echo _escape($sitename); ?></a> محفوظ است.</li>
                    <li class="pt20"> طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
</body>
</html>